<a href="https://colab.research.google.com/github/cosmina98/PhD/blob/main/2022/Oct/Shortest_Path_Kernel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install grakel --quiet

     |████████████████████████████████| 1.8 MB 8.9 MB/s 


# Using Grakel library

In [11]:
from grakel import GraphKernel
from grakel import Graph
from grakel.kernels import WeisfeilerLehman, VertexHistogram
from grakel import ShortestPath


In [12]:
import numpy as np
import networkx as nx


## Kernel between 2  molecules graphs 

In [13]:
H2O_adjacency = [[0, 1, 1], [1, 0, 0], [1, 0, 0]]
H2O_node_labels = {0: 'O', 1: 'H', 2: 'H'}
H2O = Graph(initialization_object=H2O_adjacency, node_labels=H2O_node_labels)
H3O_adjacency = [[0, 1, 1, 1], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]]
H3O_node_labels = {0: 'O', 1: 'H', 2: 'H', 3:'H'}
H3O = Graph(initialization_object=H3O_adjacency, node_labels=H3O_node_labels)

In [14]:
H2O_adjacency

[[0, 1, 1], [1, 0, 0], [1, 0, 0]]

The shortest path kernel which counts the number of shortest paths of equal length in two graphs 

In [15]:

sp_kernel =  ShortestPath()
#compute the graph representtaion between water and itself
sp_kernel.fit_transform([H2O])
#compute the kernel value between the graoh representation of water and hydronium
sp_kernel.transform([H3O])

array([[24.]])

## Apply normalisation

In [16]:
sp_kernel = ShortestPath(normalize=True)
sp_kernel.fit_transform([H2O])
sp_kernel.transform([H3O])

array([[0.94280904]])

#Dijkstra

Djistra algorithm  adjusted to work with NX graph from https://www.geeksforgeeks.org/python-program-for-dijkstras-shortest-path-algorithm-greedy-algo-7/

In [17]:

# for adjacency matrix representation of the graph
class Dijkstra_algorithm():
 
    def __init__(self, G):
 
        self.num_nodes = int(G.number_of_nodes())
        self.adjacency = np.array(nx.to_numpy_matrix(G))
        self.source_node=None
        self.max=10e7
 
    def printSolution(self, distance_from_source_node_to_any_other_node_vector):
        print("Source node  \tTarget_node,\tDistance from Source")
        for node in range(self.num_nodes):
            print(self.source_node, "\t\t" ,node,  "\t\t", distance_from_source_node_to_any_other_node_vector[node])

    def compute_all_the_shortest_paths(self):
        for v in range(self.num_nodes):
           self.dijkstra(v)
        
 
    # Find the vertex with
    # minimum distance_from_source_node_to_any_other_node_vectorance value, from the set of vertices
    # not yet included in shortest path tree
    def minDistance(self, distance_from_source_node_to_any_other_node_vector, shortest_path_tree_set):
 
        # Initialize minimum distance_from_source_node_to_any_other_node_vectorance for next node
        min =  self.max
 
        # Search not nearest vertex not in the
        # shortest path tree
        for v in range(self.num_nodes):
            if distance_from_source_node_to_any_other_node_vector[v] < min and shortest_path_tree_set[v] == False:
                min = distance_from_source_node_to_any_other_node_vector[v]
                min_index = v
 
        return min_index


    # Function that implements Dijkstra's single source
    # shortest path algorithm for a graph represented
    # using adjacency matrix representation
    def dijkstra(self,source_node):
        self.source_node=source_node
        distance_from_source_node_to_any_other_node_vector = [self.max] * self.num_nodes
        #distance_from_source_node_to_any_other_node_vectorance from the source node to itself is 0
        distance_from_source_node_to_any_other_node_vector[source_node] = 0
        #set the initial set False as all the nodes are unexplored
        shortest_path_tree_set = [False] * self.num_nodes
        print(self.adjacency)
        print('Initial vector of minimum distances from node 0 to others',distance_from_source_node_to_any_other_node_vector)
        print("Explored initial paths", shortest_path_tree_set,'\n')
  
       
        for _ in range(self.num_nodes):
 
            # Pick the minimum distance_from_source_node_to_any_other_node_vectorance vertex from
            # the set of vertices not yet processed.
            # u is always equal to src in first iteration
            u = self.minDistance(distance_from_source_node_to_any_other_node_vector, shortest_path_tree_set)
 
            # Put the minimum distance_from_source_node_to_any_other_node_vectorance vertex in the
            # shortest path tree
            shortest_path_tree_set[u] = True
            print('Node ', u, 'marked as visited' )
            # Update distance_from_source_node_to_any_other_node_vector value of the adjacent vertices
            # of the picked vertex only if the current
            # distance_from_source_node_to_any_other_node_vectorance is greater than new distance_from_source_node_to_any_other_node_vectorance and
            # the vertex in not in the shortest path tree
            for v in range(self.num_nodes):
                #if adjacent node
                print(' At neighbour ', v)
                if (self.adjacency[u][v] > 0 and
                    #and unvisited
                   shortest_path_tree_set[v] == False and
                    #and the previous distance connecting the f v with it s neigbour u was higher than the current distance set it to the current distan
                   distance_from_source_node_to_any_other_node_vector[v] > distance_from_source_node_to_any_other_node_vector[u] + self.adjacency[u][v]):
                    distance_from_source_node_to_any_other_node_vector[v] = distance_from_source_node_to_any_other_node_vector[u] + self.adjacency[u][v]
                    print('Min distance is: ',distance_from_source_node_to_any_other_node_vector[v])

        print('Final distance_from_source_node_to_any_other_node_vector' , distance_from_source_node_to_any_other_node_vector )
 
        self.printSolution(distance_from_source_node_to_any_other_node_vector)

In [74]:
# Driver program
g = Dijkstra_algorithm(G1)
g.dijkstra(1)
# This code is contributed by Divyanshu Mehta



[[0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]
Initial vector of minimum distances from node 0 to others [100000000.0, 0, 100000000.0]
Explored initial paths [False, False, False] 

Node  1 marked as visited
 At neighbour  0
Min distance is:  1.0
 At neighbour  1
 At neighbour  2
Node  0 marked as visited
 At neighbour  0
 At neighbour  1
 At neighbour  2
Min distance is:  2.0
Node  2 marked as visited
 At neighbour  0
 At neighbour  1
 At neighbour  2
Final distance_from_source_node_to_any_other_node_vector [1.0, 0, 2.0]
Source node  	Target_node,	Distance from Source
1 		 0 		 1.0
1 		 1 		 0
1 		 2 		 2.0


#Floyd-Warshall

In [24]:
class FloydWarshall_algorithm():

  def __init__(self, G):
  
          self.num_nodes = int(G.number_of_nodes())
          self.adjacency = np.array(nx.to_numpy_matrix(G))
          print('The H30 matrix\n',  self.adjacency)
          #add some random weights to the adjency to mimick the weightred graph
          self.weights=  np.random.randint(5,9,size=(self.adjacency.shape[0],self.adjacency.shape[0]))
          #self.adjacency=self.adjacency*self.weights
          self.adjacency[self.adjacency==0] = np.inf
          self.adjacency[range(self.num_nodes), range(self.num_nodes)] = 0
          print('Initial weighted adj matrix  with some random weight integer added and infinity where there s no edge\n',self.adjacency )
          self.max=np.inf
          self.dist=list(map(lambda i: list(map(lambda j: j, i)), self.adjacency))

  def floydWarshall(self):
      for k in range(self.num_nodes):
          # pick all nodes as source one by one
          for i in range(self.num_nodes):
              # Pick all nodes as destination for the above picked source
              for j in range(self.num_nodes):
                  # If node k is on the shortest path from i to j, then update the value of dist[i][j]
                  self.dist[i][j] = min(self.dist[i][j],
                                  self.dist[i][k] + self.dist[k][j]
                                  )
      self.printSolution(self.dist)
  
  # A utility function to print the solution
  def printSolution(self,dist):
      print("Following matrix shows the shortest distances\
  between every pair of nodes")
      for i in range(self.num_nodes):
          for j in range(self.num_nodes):
              if(dist[i][j] == self.max):
                  print("%2s" % ("INF"), end="")
              else:
                  print("%2d " % (dist[i][j]), end='')
          print(" ")
      return dist[i][j]
  
  def __call__(self):
        self.floydWarshall()

In [75]:
run=FloydWarshall_algorithm(G1.to_directed())
run()

The H30 matrix
 [[0. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]
Initial weighted adj matrix  with some random weight integer added and infinity where there s no edge
 [[ 0.  1.  1.]
 [ 1.  0. inf]
 [ 1. inf  0.]]
Following matrix shows the shortest distances  between every pair of nodes
 0  1  1  
 1  0  2  
 1  2  0  


In [76]:
G2.to_directed()

In [ ]:
G2.edges

In [ ]:
np.array(H2O_adjacency).shape[0]

#Function to work with NX graphs



## Implementation based on https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=1565664&tag=1

https://github.com/emanuele/jstsp2015/blob/master/gk_shortest_path.py
https://networkx.org/documentation/networkx-1.9/_modules/networkx/algorithms/shortest_paths/dense.html#floyd_warshall_numpy

In [73]:
def compare(g_1, g_2, verbose=False,nodelist=None):
        """Compute the kernel value (similarity) between two graphs.
        Parameters
        ----------
        g1 : networkx.Graph
            First graph.
        g2 : networkx.Graph
            Second graph.
        Returns
        -------
        k : The similarity value between g1 and g2.
        """
        # Diagonal superior matrix of the floyd warshall shortest
        # paths:
        A = nx.to_numpy_matrix(g_1,nodelist=nodelist, nonedge=np.inf, multigraph_weight=min,weight='weight')
        B= nx.to_numpy_matrix(g_2,nodelist=nodelist,nonedge=np.inf, multigraph_weight=min,weight='weight')
        s1 = np.triu(s1, k=1)
        count1,val1 = np.unique(s1, return_counts=True)

        s2 = np.triu(s2, k=1)
        count2,val2 =  np.unique(s2, return_counts=True)

        # Copy into arrays with the same length the non-zero shortests
        # paths:
        e1 = np.zeros(max(len(val1), len(val2)) - 1)
        e1[range(0, len(val1)-1)] = val1[1:]

        e2 = np.zeros(max(len(val1), len(val2)) - 1)
        e2[range(0, len(val2)-1)] = val2[1:]

        
        return np.sum(e1 * e2)


def compare_normalized(g_1, g_2, verbose=False):
        """Compute the normalized kernel value between two graphs.
        A normalized version of the kernel is given by the equation:
        k_norm(g1, g2) = k(g1, g2) / sqrt(k(g1,g1) * k(g2,g2))
        Parameters
        ----------
        g1 : networkx.Graph
            First graph.
        g2 : networkx.Graph
            Second graph.
        Returns
        -------
        k : The similarity value between g1 and g2.
        """
        return compare(g_1, g_2) / (np.sqrt(compare(g_1, g_1) *
                                                 compare(g_2, g_2)))

## Testing to see if we get a similar score using custom implementation 

In [34]:
def get_nxgraph_from_adjanecy_matrix(adjacency_matrix):
    rows, cols = np.where(adjacency_matrix == 1)
    edges = zip(rows.tolist(), cols.tolist())
    gr = nx.Graph()
    all_rows = range(0, adjacency_matrix.shape[0])
    for n in all_rows:
        gr.add_node(n)
    gr.add_edges_from(edges)
    gr.add_edges_from(edges)
    return gr


In [35]:
G1=get_nxgraph_from_adjanecy_matrix(np.array(H2O_adjacency))
G2=get_nxgraph_from_adjanecy_matrix(np.array(H3O_adjacency))


In [36]:
compare(G1, G2, verbose=False)

9.0

In [31]:
compare_normalized(G1, G2, verbose=False)

0.9486832980505138

In [ ]:
G1.nodes

In [38]:
G1.edges

EdgeView([(0, 1), (0, 2)])

In [55]:
fwm1 = np.array(nx.floyd_warshall_numpy(G1))
print(fwm1)
fwm1 = np.where(fwm1 == np.inf, 0, fwm1)
fwm1 = np.where(fwm1 == np.nan, 0, fwm1)
fwm1 = np.triu(fwm1, k=1)
bc1 = np.bincount(fwm1.reshape(-1).astype(int))
print(bc1)

fwm2 = np.array(nx.floyd_warshall_numpy(G2))
fwm2 = np.where(fwm2 == np.inf, 0, fwm2)
print(fwm2)
fwm2 = np.where(fwm2 == np.nan, 0, fwm2)
fwm2 = np.triu(fwm2, k=1)
print(fwm2)

bc2 = np.bincount(fwm2.reshape(-1).astype(int))
print(bc2)

# Copy into arrays with the same length the non-zero shortests
# paths:
v1 = np.zeros(max(len(bc1), len(bc2)) - 1)
print(v1)
v1[range(0, len(bc1)-1)] = bc1[1:]
print(v1)

v2 = np.zeros(max(len(bc1), len(bc2)) - 1)
print(v2)

v2[range(0, len(bc2)-1)] = bc2[1:]
print(v2)

 
np.sum(v1 * v2)


[[0. 1. 1.]
 [1. 0. 2.]
 [1. 2. 0.]]
[6 2 1]
[[0. 1. 1. 1.]
 [1. 0. 2. 2.]
 [1. 2. 0. 2.]
 [1. 2. 2. 0.]]
[[0. 1. 1. 1.]
 [0. 0. 2. 2.]
 [0. 0. 0. 2.]
 [0. 0. 0. 0.]]
[10  3  3]
[0. 0.]
[2. 1.]
[0. 0.]
[3. 3.]


9.0

In [72]:
s1 = np.array(nx.floyd_warshall_numpy(G1))
s2 = np.array(nx.floyd_warshall_numpy(G2))
s1 = np.triu(s1, k=1)
count1,val1 = np.unique(s1, return_counts=True)

s2 = np.triu(s2, k=1)
count2,val2 =  np.unique(s2, return_counts=True)

# Copy into arrays with the same length the non-zero shortests
# paths:
e1 = np.zeros(max(len(val1), len(val2)) - 1)
e1[range(0, len(val1)-1)] = val1[1:]

e2 = np.zeros(max(len(val1), len(val2)) - 1)
e2[range(0, len(val2)-1)] = val2[1:]

 
np.sum(e1 * e2)

9.0